name: CwCastle
favicon: null
layout_spectrum: 1
typography_spectrum: 0.54543
title: CwCastle Associates
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eff3fc'
    - '#c5824d'
    - '#37383d'
    - '#3e76c3'
    - '#cc0f34'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
