name: CwCastle
favicon: null
layout_spectrum: 0.6034095226787031
typography_spectrum: 0.3228863284457475
title: CwCastle Associates
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.08097187685780227
  lightness: 0.5293995204847306
  saturation: 0.5373206024523824
  rhythmicContrast: 0.3719232608564198
purpose: []
