analytics: {}
color:
  brandColors:
    - '#eff3fc'
    - '#c5824d'
    - '#37383d'
    - '#3e76c3'
    - '#cc0f34'
  brandStrength: 0.5
  lightness: 0.5
  rhythmicContrast: 0.5
  saturation: 0.5
cta: {}
layout_spectrum: 1
name: CwCastle
opengraph: {}
purpose: []
typography_spectrum: 0.134868
