analytics: {}
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0
  lightness: 0.8125
  rhythmicContrast: 0.25
  saturation: 0.25
cta: {}
layout_spectrum: 0.807566
name: CwCastle
opengraph: {}
purpose: []
typography_spectrum: 0.54543
